### ISSUE TITLE
Datepicker as a popup

### ISSUE THREAD

**Issue by Simplelenz** [misha130/ion-datepicker#45]
Hello,

Can we add this datepicker as a pop instead of a modal? Thanks

**Comment by misha130** [comment]
You mean you want to make the modal size smaller?
A modal is a popup that just takes the whole screen. You can adjust it via
css.
Take a look how it will display in iPad size.

**Comment by Simplelenz** [comment]
Yes, I checked it as you mentioned and that is what I want thanks. how to customize the size and other styles? I tried accessing scss variables in the datepicker.component.scss in my pages scss file. But it seems not working. Any help?

**Comment by misha130** [comment]
The datepicker component scss is just a help file so I can see the
formatting. The real is css is in the datepicker.component.ts in styles.

This is because the build process is already complicated and I dont want to
make it more complicated.

**Comment by Simplelenz** [comment]
I tried changing the header color using the below  code in my pages .scss file
`ionic2-datepicker .datepicker-wrapper .datepicker-header {
        color: white;
        background-color: #310096;
        display: flex;
        flex-flow: column;
        height: 35%;
      }`
but it is not working. Can't I customize the datepicker by overriding the style variables externally without making changes to the datepicker.component.ts

**Comment by misha130** [comment]
Sorry I assumed that you forked the project since you mentioned the scss file.

Here is my overload:
```
ionic2-datepicker,
ionic2-datepicker .datepicker-wrapper {
    background: linear-gradient(135deg, #172446 0%, #2a3c60 26%, #5393ae 61%, #5393ae 66%, #335e88 81%, #336084 100%);
    .datepicker-header {
        background-color: rgba(0, 0, 0, 0.25)!important;
        .weekday-header {
            background-color: rgba(0, 0, 0, 0.25)!important;
        }
    }
    .button {
        background-color: rgba(0, 0, 0, 0.25)!important;
    }
    .row {
        color: white!important;
        .datepicker-selected {
            color: black;
        }
        .datepicker-current {
            color: #bdbdbd;
        }
    }
}

```
