### ISSUE TITLE
Problem with year , month and date select

### ISSUE THREAD

**Issue by sujiththakur** [misha130/ion-datepicker#46]
When we select a year from the dropdown option, the year is getting selected but after the year is selected, you go and select the date from calendar, the year is changing again by itself. 
Please look into this issue.

**Comment by misha130** [comment]
Thanks fixed in 2.6.5.

Funny I saw this in a fork https://github.com/wesleyluan/datepicker-ionic2-wesdias/commit/3237a4df1e8c89e15e5e0c64731e00c07f6f53f7 and didn't understand why this was.

**Comment by sujiththakur** [comment]
I have one more issue Misha, when I try to change the month from the dropdown option, I am not able to see January month from the list. It starts from Feb, please look into this issue as well. Thanks.

**Comment by misha130** [comment]
Fixed in 2.6.7.

Thanks!
