### ISSUE TITLE
ionSelected function

### ISSUE THREAD

**Issue by niklilland** [misha130/ion-datepicker#49]
Hey, I'm really liking this library! I am curious if the ionSelected function found on the interface is going to be implemented? I see it's in the code, but not in the Readme. For the functionality I'm looking for, I need to have a function to handle every time a date is selected. 

Thanks!

**Comment by misha130** [comment]
It used to be there, it used to work, it was implemented and tested.

I am confused.
I'll add back as soon as I can.
