### ISSUE TITLE
Dismiss from directive oncorrect

### ISSUE THREAD

**Issue by niklilland** [misha130/ion-datepicker#50]
The example in the Readme file for dismissing the datepicker through the class is incorrect. It should be this:

### Dismiss the datepicker from the class  ###

```

    import { DatePickerDirective } from 'ion-datepicker';

	@ViewChild(DatePickerDirective) private datepickerDirective:DatePickerDirective;

    public closeDatepicker(){
        this.datepickerDirective.modal.dismiss();
    }
    
```

Note this is ionic 3.6.1

**Comment by misha130** [comment]
Thanks, will do.
Or you can PR it, will be quicker
