### ISSUE TITLE
need compact design in desktop version

### ISSUE THREAD

**Issue by nidhi1612** [misha130/ion-datepicker#55]
Hi,
I am planning to use ion-datepicker for both mobile devices and desktop. For mobile devices the look is perfect usability wise. But in desktop full screen date picker looks a bit weird. Is there a way to have a small size date picker for desktop. 
I can see that in previous version there was a full property which isn't there now. Can you please guide me with the same. 
Thanks in advance.

**Comment by misha130** [comment]
Well you can add a class to the modal itself using the modal options

```
<span ion-datepicker [modalOptions]="{'cssClass':'full'}"
  [(value)]="localDate" [min]="localDate" clear class="ScheduleDate">
		<span>{{localDate | date}}</span>
	</span>
```

And then you can make a css class like this:
```
.full { 
  @media only screen and (min-height: 600px) and (min-width: 768px)
    .modal-wrapper {
        left: 0;
        top: 0;
        position: absolute;
        width: 100%;
        height: 100%;
   }
}
```

This will make it full screen which is the same as the full option it once had.
I just don't know how exactly you want it to look.

**Comment by nidhi1612** [comment]
works perfectly. Thank you so much. 👍
