### ISSUE TITLE
Can disable Day of Week ?

### ISSUE THREAD

**Issue by rainhaha** [misha130/ion-datepicker#59]
Can disable Day of Week ? Example All disable Example Disable Saturday and Sunday

**Comment by rainhaha** [comment]
please help me bro

**Comment by misha130** [comment]
Ok mate:

First build a function that gets all the weekday days

```
 getWeekdays(date, weekday) {
    if(weekday < 0 || weekday > 6) return [];
    var d = date || new Date(),
        month = d.getMonth(),
        weekdays = [];

    d.setDate(1);

    // Get the first Weekdays in the month
    while (d.getDay() !== weekday) {
        d.setDate(d.getDate() + 1);
    }

    // Get all the other Weekdays in the month
    while (d.getMonth() === month) {
        weekdays.push(new Date(d.getTime()));
        d.setDate(d.getDate() + 7);
    }

    return weekdays;
}
```

Lets all saturdays and sundays are off so

`disabledDates = [...getWeekdays(new Date(), 6), ...getWeekdays(new Date(), 0)]`

Then in HTML just add 

`[disabledDates]="disabledDate"` on the element

**Comment by rainhaha** [comment]
thanks you now i can disabled date and day(0,6) on ionic

  disabledDates2:any = [new Date(2018, 0, 11),new Date(2018, 0, 10),new Date(2018, 0, 12)]
  disabledDates3:any = this.getWeekdays(new Date(), 0)
  disabledDates:any = this.getWeekdays(new Date(), 6)
  
a = Array.prototype.push.apply(this.disabledDates, this.disabledDates3);
b = this.disabledDates.push(new Date(2018, 0, 11),new Date(2018, 0, 10),new Date(2018, 0, 12))

work for me thanks
