### ISSUE TITLE
An empty element appears in month and year combobox 

### ISSUE THREAD

**Issue by adriansaenz** [misha130/ion-datepicker#60]
When you open the combobox, appears in the beginning an empty element. Appears over January and over 1900. The date that returns when you select this elements is December 1900. In the source code I see that there is an empty field <option> in datepicker.component.html file that it is causing the problem. Can you fix it?

**Comment by misha130** [comment]
I looked and didn't find any of those empty items. Could you attach a picture?
Also datepicker.component.html is obsolete.

**Comment by misha130** [comment]
Realized this was https://github.com/pauloedsr/ionic3-datepicker fork.
Closed
