### ISSUE TITLE
how to close modal when push another page 

### ISSUE THREAD

**Issue by ipehimanshu** [misha130/ion-datepicker#62]
Hello 
We are creating app using ionic 3.
We are using push notification and when we click on notification we need to redirect user to that page. 
all things perfect except this date picker not closed .

Any way to close this date picker from any other place. 
if yes then it will be great help for us.

Thanks

**Comment by misha130** [comment]
Look at the readme, it has this example: 
`import { DatePickerDirective } from 'ion-datepicker';

	@ViewChild(DatePickerDirective) private datepickerDirective:DatePickerDirective;

    public closeDatepicker(){
        this.datepickerDirective.modal.dismiss();
    }
`

**Comment by ipehimanshu** [comment]
ok thank you. 
but how to know that date picker open . 

let me explain my case. 
i have overlap modal popup case so i have created one service and in that service i will push those modal instance so when i am changing page i will dismiss those popup from array.

But for this ion date picker i am not able to push into service . because this modal popup open by Directive.

Is there any way to open manually modal popup on click event so we can track it and close ?

Thanks

**Comment by misha130** [comment]
The DatePickerDirective has a public open event. 
It also has a public modal property which is the open modal that is presented. 
The modal property is essentially an ionic modal, it has events such as DidLeave, WillLeave, etc.

**Comment by ipehimanshu** [comment]
In date picker is that type any possibilities to open manually modal ?

Thanks 
![image](https://user-images.githubusercontent.com/26652038/36710600-09c03088-1ba5-11e8-9ae9-57793fd42502.png)

**Comment by misha130** [comment]
@ViewChild(DatePickerDirective) private datepickerDirective:DatePickerDirective;

public openDatepicker(){
    this.datepickerDirective.open();
}

**Comment by ipehimanshu** [comment]
ok big thanks.

But how to do like if we have already date and when open modal popup by default set added date.

In imageviewer ionic plugin they provide like present and create option so we can set whole image tag but in date picker we may need value and other things so can you please create small code form me if you have little time.

Sorry in advance.
