### ISSUE TITLE
markDates not working for iPhone 5

### ISSUE THREAD

**Issue by warjohn123** [misha130/ion-datepicker#63]
Hi,

I was using this directive and it's working fine for iPhone 5 except for markDates.

**Comment by arcanys-ivan** [comment]
not working in other iPhones as well, `datepicker-mark` class is not added

**Comment by misha130** [comment]
If anyone could provide a screenshot or an error message I could solve
this. But alas it takes time to get an iphone 5

**Comment by arcanys-ivan** [comment]
no error message, I guess its because of the date comparison, as safari has formats that are not supported,

**Comment by arcanys-ivan** [comment]
you can test it on safari browsers even on PCs

**Comment by misha130** [comment]
I teamviewed a mac and tested it:
https://i.gyazo.com/d43d99c327a200de79999a5de99e8b5f.png

Are you guys adding an array of Date instances? or strings?
Cause its supposed to be Date instances

**Comment by arcanys-ivan** [comment]
hi @misha130 thanks for your response, but Ive found out that it is our date conversion that is wrong. as safari does not allow date conversion from dateString, thanks for your response.

Thanks also for this awesome library ;)
