### ISSUE TITLE
Several issues after having installed it

### ISSUE THREAD

**Issue by Youtch** [misha130/ion-datepicker#66]
Hello,
I find two differens errors actually, after have followed the installation instruction, and have included the sample given in the readme to display the span"button" : it displays well the date if i defined the now date for the variable attribute  named "localeDate". 
After that, I get the correct displaying of the modal on all the screen, but strangely the style aren't totally correct : 
![demoview 1](https://user-images.githubusercontent.com/8899768/38055589-6cd77554-32da-11e8-8fed-edbc59049f61.jpg)
See that the numbers of days aren't well aligned in the grid but squeezed on center, secondly the day's names of week are dispatched at several lines.
How to resolve it ?

Maybe this issue could be explained with it : 
the "locale" attribute of "span" markup don't working, tested with several locales codes presents in Readme.md ; Otherwise the cancel attribut don't working nor.

**Tested on Chrome "DevTool" with...**
```
<span  style="width:100%" ion-datepicker  [(value)]="localDate" [min]="localDate" [locale]="fr-FR"  [cancelText]="Annuler" clear class="ScheduleDate">
  <span style="width:100%">changge date</span>
</span>
```

**Comment by Youtch** [comment]
Moreover I received this log after having tryed to compile a release to run the app on a device :
> [23:23:01]  ngc started ...
> Error: Metadata version mismatch for module C:/Users/PC/Projects/sdaot/node_modules/ion-datepicker/module/datepicker.module.d.ts, found version 4, expected 3
>     at StaticSymbolResolver.getModuleMetadata (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:25755:34)
>     at StaticSymbolResolver._createSymbolsOf (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:25543:46)
>     at StaticSymbolResolver.getSymbolsOf (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:25524:14)
>     at C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:24381:30
>     at Array.forEach (<anonymous>)
>     at extractProgramSymbols (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:24380:79)
>     at AotCompiler.analyzeModulesAsync (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler\bundles\compiler.umd.js:23936:47)
>     at CodeGenerator.codegen (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
>     at Function.NgTools_InternalApi_NG_2.codeGen (C:\Users\PC\Projects\sdaot\node_modules\@angular\compiler-cli\src\ngt
> ools_api.js:73:30)
>     at C:\Users\PC\Projects\sdaot\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:182:73
> [23:23:16]  copy finished in 19.30 s

**Comment by misha130** [comment]
Well its because I didn't push the package-lock.json.
You can pull and delete node modules and it'll be fine or delete package-lock.
Either way

**Comment by Youtch** [comment]
I deleted node_modules, and package-lock.json in the folder named '[PROJECT_FOLDER]\node_modules\ion-datepicker'. So I run as at the previous trying
`ionic cordova build android -p 8300 --prod --debug --device`
I receive again the same error.
I tryed npm install and re-run by it doesn't works.

**Comment by misha130** [comment]
You are trying to run the demo, right?
So the node_modules are in demo/ 
You cant run the root project as is because its just the module.

**Comment by Youtch** [comment]
When sending question I was using my own project not the demo, and it wasn't working.
Secondly I'm going to implement my source in the project's folder of the demo, it seems to work well as it. Thanks for help.
FG
