### ISSUE TITLE
minimum date that user is allowed to select. (not required) not working

### ISSUE THREAD

**Issue by ipehimanshu** [misha130/ion-datepicker#68]
Hello 

if i set min value for today date then i am not able to see any current month in calendar .

is it bug or i am missing anything ?

Case is 

public registration_date_inputDate:Date=new Date(2017,10,20);

public localDate: Date = new Date();

<span ion-datepicker [(value)]="registration_date_inputDate" [min]="localDate" clear class="ScheduleDate">
      <span>{{localDate | date}}
        <ion-icon name="clipboard" item-left></ion-icon>
      </span>
    </span>

then when i open calendar it missed current month calendar

can you please help me.

**Comment by chipsnpieces** [comment]
Hi ipehimanshu,

I am facing the same issue. Did you found the solution or any workaround. I would really appreciate if you can help.

**Comment by ipehimanshu** [comment]
no 
i have used as it is now 
and when user select date i will check date and give error message if past as per my logic.

**Comment by misha130** [comment]
Fixed in 2.7.6.
