### ISSUE TITLE
min date feature is not working as expected

### ISSUE THREAD

**Issue by hparth** [misha130/ion-datepicker#70]
Minimum date feature is not working. When you keep mean date except 1st day of month, you can't select any date of that month.

Like if let's say current date is 10th April 2018 and min date is 8th Jan 2018, I can go back until Feb month only but can't go till Jan month. If min date is 1st Jan then and then can select any date of Jan month.

**Comment by misha130** [comment]
Fixed in 2.7.6.

**Comment by ipehimanshu** [comment]
from where we can download it.
