### ISSUE TITLE
Facing issues in Lazy Loading

### ISSUE THREAD

**Issue by Afarooq143** [misha130/ion-datepicker#72]
Hi it worked fine for me til i had to make changes in my App to implement Lazy Loading and i'm getting following errors please help me out

I'm calling datepicker modal from my Sign Up page to enter dob & on click i call function to display datepicker.

_**Error:**_
![date err](https://user-images.githubusercontent.com/16359312/39046637-812810b8-44b4-11e8-8a33-753fe8434f51.PNG)

**_DatePicker Calling Form_**
![date err2](https://user-images.githubusercontent.com/16359312/39046760-e9026daa-44b4-11e8-896b-ec9d1d9fea46.PNG)

**_Code_**
_Template_: 
<ion-item no-padding>
            <ion-label floating>Date of Birth</ion-label>
            <ion-input [formControl]="signupForm.controls['date_of_birth']" [(ngModel)]="date_of_birth" (click)="showCalendar()" [ngClass]="{'error-border':!signupForm.controls['date_of_birth'].valid}"></ion-input>
</ion-item>

**_Component_**

showCalendar() {
    const dateSelected =
      this.datePickerProvider.showCalendar(this.modalCtrl);
    dateSelected.subscribe(date =>
      this.date_of_birth = this.dateFormat.transform(date, 'MM/dd/yyyy')
    );
  }

**_Note:_** Remember it was working fine till i implemented Lazy Loading.

Please help

**Comment by misha130** [comment]
Try and add 
    IonicPageModule.forChild(DatePicker),
In your page module as a work around.
Tell me if it works.

**Comment by SatyaHarishMeka** [comment]
Hi i am also getting problem with lazy loading. In my case i am getting error as

**Comment by misha130** [comment]
Tested today, works.
I made a branch that checks if it works:
https://github.com/misha130/ion-datepicker/tree/lazy

**Comment by SatyaHarishMeka** [comment]
Thanks for your response.  I to done the same, it is working fine. But my problem is we imported DatePickerModule 2 times.
One in lazy.module.ts  and in app.module.ts. 
Can i make it work by adding only in  lazy.module.ts (i.e by removing it from app.module.ts)

Because my splash screen is taking soo much time if we are adding more load on app.module
