### ISSUE TITLE
2.7.6 latest plugin version next , previous button in datepicker not working

### ISSUE THREAD

**Issue by ipehimanshu** [misha130/ion-datepicker#73]
![image](https://user-images.githubusercontent.com/26652038/39227080-442ec21a-4874-11e8-8601-cdf7126cfc1b.png)

When press previous or next button it shows error

**Comment by misha130** [comment]
Thank you so much for your report.
I fixed this and released 2.7.7.

**Comment by ipehimanshu** [comment]
thanks for quick reply.


On Wed, Apr 25, 2018 at 5:02 PM, Misha Tarnorutsky <notifications@github.com
