### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by samuelbigard** [misha130/ion-datepicker#78]
Hi,

I would like to know if we can personalize the background color which is actually green ?

On the top, the month is not write totally (Jun for June), can we change this to display all the month ?

Thanks

**Comment by misha130** [comment]
Can use for months
[localeStrings] and set the months by yourself:
`[localeStrings] - if you dont want to use the built translations - accepts an object { weekdays: string[], months: string[], monday:boolean }, For example: { monday:true, weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'], months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'] },`

Here is an example for the background color:

```
ionic2-datepicker, ionic2-datepicker .datepicker-wrapper{
background:linear-gradient(135deg, #172446 0%, #2a3c60 26%, #5393ae 61%, #5393ae 66%, #335e88 81%, #336084 100%)!important;
    .datepicker-header{
                           background-color:rgba(0,0,0,0.25)!important;
                           .weekday-header{
                                  background-color:rgba(0,0,0,0.25)!important;
                           }
    }
    .button{
                                          background-color:rgba(0,0,0,0.25)!important;

    }
         .row {
         color:white!important;
         .datepicker-selected{
             color:black;
         }
         .datepicker-current{
             color:#bdbdbd;
         }
     }
}
```
