### ISSUE TITLE
Error: Type Page is part of the declarations of 2 modules

### ISSUE THREAD

**Issue by rainhaha** [misha130/ion-datepicker#80]
If I create Page On Tabs 
![image](https://user-images.githubusercontent.com/23095185/41590176-92802610-73e0-11e8-95bf-ba7f65de6b69.png)

When I open Tabs SearchPage Will Error 

![image](https://user-images.githubusercontent.com/23095185/41590217-b144b106-73e0-11e8-8d3f-e70555aef5c4.png)

I try moving SearchPageModule to imports and delete SearchPage in declarations and entryComponents 

![image](https://user-images.githubusercontent.com/23095185/41590416-22f1497c-73e1-11e8-817d-779895bf2e8e.png)

When I click picture ,  Datepicker  Can't Open 

Please Help me and Sorry , I'm not good English

**Comment by misha130** [comment]
Import DatepickerModule in to SearchPageModule and not into AppModule.
Don't forget imports always import DOWN not UP
