### ISSUE TITLE
Incorrect marked dates (dates are one day out)

### ISSUE THREAD

**Issue by sanctus671** [misha130/ion-datepicker#82]
Firstly love the plugin. Definitely the best date picker out there for Ionic.

I'm having a problem where the marked dates on the calendar are 1 day out. See this image for example: 

![unnamed](https://user-images.githubusercontent.com/8212487/42408528-30c2f2f4-8222-11e8-9bb5-86c6093b5cdf.png)

The dates that are being set as the marked dates are:
2018-05-17
2018-05-19
2018-05-20
2018-05-22
2018-05-24
2018-05-26
2018-06-02
2018-06-05
2018-06-09

As you can see, each of the dates that are marked in the calendar are 1 day off.

Unfortunately I can't actually replicate the issue myself, this is only reports I have got from a couple of users of my app. I'm a bit stuck as I can't seem to see any reason why this could be happening. Do you know why this could be happening and how I can fix it?

**Comment by misha130** [comment]
I think you are sending out strings of dates instead of instances of dates.
Let the marked Dates array be instances of dates and it should be fixed

**Comment by sanctus671** [comment]
Thanks for the reply. I was actually already converting them to Date objects, however the issue was actually related to javascripts date parsing and differant time zones. My date strings were in the format yyyy-mm-dd and hence were parsed as ISO 8601 when using `new Date(myDate) ` and gave the wrong date for some timezones. Changing the hyphens to slashes means the date is parsed as RFC 2822 which uses local time when the timezone is absent. In summary, I changed `new Date(myDate)` to `new Date(myDate.replace(/-/g, '\/'))`. See this thread for more info: [(https://stackoverflow.com/questions/7556591/javascript-date-object-always-one-day-off)]
