### ISSUE TITLE
Any way to format Date()?

### ISSUE THREAD

**Issue by theparmis** [misha130/ion-datepicker#83]
Hello everybody,
Any help for format Date() in typescript?

Thanks!

**Comment by misha130** [comment]
Angular has a pipe called date for the html that formats
https://angular.io/api/common/DatePipe

**Comment by theparmis** [comment]
Thanks for your response,

I used this function to set ion-datepicker value to my input value like this:
<code>
setDate(date: Date) {
    console.log(date);
    this.initDate = date;
    this.mydatefield= date;  //  save date to my date field - mydatefield is already defined.
  }
</code>
And it seems it not appropriate to use DatePipe to format "this.mydatefield" like "yyyy/MM/dd".

Can i still use DatePipe for this problem? 

Thanks!

**Comment by theparmis** [comment]
Any idea?
Thanks!

**Comment by misha130** [comment]
Glad you figured it out.
