### ISSUE TITLE
Template parse errors:

### ISSUE THREAD

**Issue by peterkhang** [misha130/ion-datepicker#84]
Your demo sources work good.
I copied your demo's home page source into my BranchPage source.
But my Ionic BranchPage with your custom datepicker control generate a error as following...

compiler.js:466 Uncaught Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'span'. ("!--<ion   #dateTime [(ngModel)]="hiddenDate" [hidden]="true"></ion>-->
        <span ion-datepicker [ERROR ->][(value)]="initDate" locale="en-US" clear class="ScheduleDate">
          <span>{{initDate | date}}
 "): ng:///BranchPageModule/BranchPage.html@19:29
    at syntaxError (compiler.js:466)
    at TemplateParser.parse (compiler.js:24329)
    at JitCompiler._parseTemplate (compiler.js:33757)
    at JitCompiler._compileTemplate (compiler.js:33732)
    at compiler.js:33634
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:33634)
    at compiler.js:33504
    at Object.then (compiler.js:455)
    at JitCompiler._compileModuleAndComponents (compiler.js:33503)

**Comment by misha130** [comment]
You didnt import the datepicker module in the current module. Thats why the
error.

**Comment by peterkhang** [comment]
export declare module nls {
    const _nls: {
        'custom': {};
        'ko-KR': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'en-US': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'en-UK': {
            weekdays: string[];
            months: string[];
        };
        'pt-BR': {
            weekdays: string[];
            months: string[];
        };
        'es-ES': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'gl-ES': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'he-IL': {
            weekdays: string[];
            months: string[];
        };
        'ru-RU': {
            weekdays: string[];
            months: string[];
        };
        'de': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'fi': {
            weekdays: string[];
            months: string[];
        };
        'fr-FR': {
            monday: boolean;
            weekdays: string[];
            months: string[];
        };
        'zh-CN': {
            weekdays: string[];
            months: string[];
        };
        'zh-TW': {
            weekdays: string[];
            months: string[];
        };
        'ja-JP': {
            weekdays: string[];
            months: string[];
        };
    };
    function getWeekdays(locale: languages): string[];
    function getMonths(locale: languages): string[];
    function getNls(locale: languages): {
        weekdays: string[];
        months: string[];
        monday: boolean;
    };
    function checkExists(locale: string): boolean;
}
export declare type languages = string | 'ko-KR' | 'en-US' | 'en-UK' | 'pt-BR' | 'es-ES' | 'gl-ES' | 'he-IL' | 'ru-RU' | 'de' | 'fi' | 'fr-FR' | 'zh-TW' | 'zh-CN' | 'ja-JP' | 'custom';

**Comment by peterkhang** [comment]
Thank you so much for your response !!!

I added  
import { DatePickerModule } from 'ion-datepicker';
into branch.module.ts like following : 

import { NgModule, CUSTOM_ELEMENTS_SCHEMA} from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { BranchPage } from './branch';
import { HeaderModule } from '../header/header.module' ;
import { DatePickerModule } from 'ion-datepicker';

@NgModule({
declarations: [
BranchPage
],
imports: [
HeaderModule,
DatePickerModule,
IonicPageModule.forChild(BranchPage),
],
schemas: [ CUSTOM_ELEMENTS_SCHEMA ],
entryComponents: [BranchPage]
})
export class BranchPageModule {}

Now It works fine.

**Comment by peterkhang** [comment]
I  added weekdays for "ko-KR" locale like following :

[nls.js]
'ko-KR': {
            monday: true,
            weekdays: ['월요일', '화요일', '수요일', '목요일', '금요일', '토요일', '일요일'],
            months: ['1월', '2월', '3월', '4월', '5월', '6월', '7월', '8월', '9월', '10월', '11월', '12월']
        },

If you don't mind, I ask you to add ko-KR locale into your repository sources(nls.d.ts, nls.js).

Thank you in advance!!!
